main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.MainView.as_view()),
    path('about_me/', views.AboutMeView.as_view()),
    path('skill/', views.SkillView.as_view()),
]

team_project/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
]

main/models.py
from django.db import models

class Member(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    photo_path = models.CharField(max_length=255)

    def __str__(self):
        return f'[{self.pk}] {self.name}'

class Career(models.Model):
    member_pk = models.ForeignKey(Member, on_delete=models.CASCADE)
    career = models.TextField()
    
    def __str__(self):
        return f'[{self.member_pk}] {self.pk}'

class ContactCategory(models.Model):
    name = models.CharField(max_length=30)
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Contact(models.Model):
    member_pk = models.ForeignKey(Member, on_delete=models.CASCADE)
    category = models.ForeignKey(ContactCategory, on_delete=models.CASCADE)
    url = models.URLField()

    def __str__(self):
        return f'[{self.member_pk}] {self.category}'

class SkillCategory(models.Model):
    name = models.CharField(max_length=30)
    icon_path = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Skill(models.Model):
    member_pk = models.ForeignKey(Member, on_delete=models.CASCADE)
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.member_pk}] {self.category}'

class Portfolio(models.Model):
    member_pk = models.ForeignKey(Member, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    photo_path = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return f'[{self.member_pk}] {self.title}'

class Hobby(models.Model):
    member_pk = models.ForeignKey(Member, models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo_path = models.CharField(max_length=255)

    def __str__(self):
        return f'[{self.member_pk}] {self.title}'

main/views.py
from django.shortcuts import render

from django.views.generic import ListView
from .models import Member, Career, Contact

from django.views import View

from django.views.generic import TemplateView

class MainView(ListView):
    model = Member
    template_name = 'main/main.html'

class AboutMeView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        context['member'] = Member.objects.get(pk=request.GET['pk'])
        context['careers'] = Career.objects.filter(pk=request.GET['pk'])
        context['contacts'] = Contact.objects.filter(pk=request.GET['pk'])

        return render(request, 'about_me/about_me.html', context)
    
class SkillView(TemplateView):
    template_name = 'skill/skill.html'

main/templates/about_me/about_me.html
{% extends 'content_base/content_base.html' %}

{% load static %}

{% block css_link %}
<link href="{% static 'css/about_me.css' %}" type="text/css" rel="stylesheet">
{% endblock css_link %}

{% block title %}
	About Me
{% endblock title %}

{% block content %}
<div id="profile-background">
	<div id="profile">
		<table id="profile-table">
			<tr>
				<td rowspan="4" id="profile-photo-cell"><img src="{% static 'img/' %}{{member.photo_path}}/profile_photo.jpg" alt="프로필 사진" id="profile-photo"></td>
				<th>Name</th>
				<td>{{member.name}}</td>
			</tr>
			<tr>
				<th>Age</th>
				<td>{{member.age}}</td>
			</tr>
			<tr>
				<th>Career</th>
				<td>
					<ol>
						{% for career in careers %}
						<li>{{career.career}}</li>
						{% endfor %}
					</ol>
				</td>
			</tr>
			<tr>
				<th>Contact</th>
				<td>
					<ol>
						{% for contact in contacts %}
						<li>{{contact.category}}</li>
						{% endfor %}
					</ol>
				</td>
			</tr>
		</table>
	</div>
</div>

<input type="hidden" id="pk" value="{{member.pk}}">
{% endblock content %}

main/templates/entrance/entrance.html
<div id="entrance-block">


    <div id="entrance-background">
        <div class="wrapper"; style="margin : 100px">
            <a class="cta">
                <span>데이터 수집</span>
                <span>
                    <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
                        </g>
                    </svg>
                </span>
            </a>
        </div>
        <div class="wrapper"; style="margin : 100px">
            <a class="cta">
                <span>모델 검증</span>
                <span>
                    <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
                            <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
                        </g>
                    </svg>
                </span>
            </a>
        </div>
    </div>
</div>

main/templates/home/home.html
<div id="home">
  <section class="hero-section">
    <div class="card-grid">
      {% for member in member_list %}
      <a class="card">
        <div class="card__background" style="background-image: url('static/img/{{member.photo_path}}/home_photo.jpg');"></div>
        <div class="card__content">
          <p class="card__category">{{member.name}}</p>
          <input type="hidden" id="pk" value="{{member.pk}}">
        </div>
      </a>
      {% endfor %}
    <div>
  </section>
</div>

main/templates/main/css_link.html
{% load static %}

<link href="{% static 'css/entrance.css' %}" type="text/css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
<link href="{% static 'css/home.css' %}" type="text/css" rel="stylesheet">

main/templates/main/home_link.html
{% include 'entrance/entrance.html' %}
{% include 'home/home.html' %}

main/templates/main/main.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    {% include 'main/css_link.html' %}
    
    <script src="{% static 'js/main.js' %}"></script>

    <title>2조 자기소개 Homepage</title>
</head>
<body>

    {% include 'main/home_link.html' %}

</body>
</html>

main/templates/skill/skill.html
{% extends 'content_base/content_base.html' %}
{% load static %}

{% block content %}

<head>
  <style>
    .container {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
    }

    .gallery {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      margin: 10px;
      width: 250px;
      height: 250px;
    }

    .gallery:hover {
      border: 2px solid #F7E600;
    }

    .gallery img {
      width: 90%;
      height: 90%;
      object-fit: contain;
    }

    .desc {
      text-align: center;
    }

  </style>
</head>

<body>
<br>
<br>
<div align="center"><h2>내가 다룰 수 있는 도구들</h2></div>
<br>

<div class="container">

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'django.png' %}" alt="장고 아이콘" id="django">
    </a>
    <div class="desc"><h3>django</h3></div>
  </div>

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'HeidiSQL_logo_image.png' %}" alt="SQL이미지">
    </a>
    <div class="desc"><h3>HeidiSQL</h3></div>
  </div>

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'java_logo.png' %}" alt="자바 이미지">
    </a>
    <div class="desc"><h3>JAVA</h3></div>
  </div>

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'JavaScript_Logo.png' %}" alt="자바스크립트 로고">
    </a>
    <div class="desc"><h3>JAVASCRIPT</h3></div>
  </div>

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'Rstudio.png' %}" alt="rsudio">
    </a>
    <div class="desc"><h3>R</h3></div>
  </div>

  <div class="gallery">
    <a target="_blank">
      <img src="{% static 'python_logo2.png' %}" alt="python">
    </a>
    <div class="desc"><h3>python</h3></div>
  </div>


</div>
</body>

{% endblock content %}